name: Learning Github Actions

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Welcome
              run: echo "My First Githun Actions"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md 

