name: Exploring Variables and Secrets

on: push

env:
    CONTAINER-REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx


jobs:
  #docker:
   ##steps:
    #- name: Docker Build
     # run: docker build -t docker.io/dockerUsername/imageName:Latest
      
    #- name: Docker Login
     # run: docker login --usernname=dockerUsername --password=s3cUrePawSsw0rd

    #- name: Docker Publish
     # run: docker push docker.io/dockerUsername/imageName:Latest
      
    #deploy:
   # needs: docker
    #runs-on: ubuntu-latest
    #steps:
    #- name: Docker Run
     # run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:Latest     

##### At Step Level ####

  #docker:
      # steps:
       # - name: Docker build
        #  env:
         #   CONTAINER-REGISTRY: docker.io
          #  DOCKER_USERNAME: seyinka
           # IMAGE_NAME: github-actions-nginx
          #run: echo  docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD 
          
       # - name: Docker Login
        #  env: 
         #   DOCKER_PASSWORD: zigizaga123
          #  DOCKER_USERNAME: seyinka
          #run: echo docker login --username=$DOCKER_USERNAME --passsword=$DOCKER_PASSWORD
          
       # - name: Docker Publish
        #  env:
         #   CONTAINER-REGISTRY: docker.io
          #  DOCKER_USERNAME: seyinka
           # IMAGE_NAME: github-actions-nginx
         # run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:Latest
          
     #deploy:
      #  needs: docker
       # runs-on: ubuntu-latest
       #steps:
        #- name: Docker Run
        #  env: 
           # CONTAINER_REGISTRY: docker.io
            #DOCKER_USERNAME: seyinka
           # IMAGE_NAME: github-actions-nginx
          #run: echo docker run -p -d 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:Latest   


##### At Job level ####

 # docker: 
 #  env:
  #    CONTAINER-REGISTRY: docker.io
   #   DOCKER_USERNAME: seyinka
    #  IMAGE_NAME: github-actions-nginx
   #runs-on: ubuntu-latest
   #steps:
   #- name: Docker Build
    # run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
   ## env:
     #   DOCKER_PASSWORD: zigizaga123
    # run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

   #- name: Docker Publish
    # run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 

 #deploy:
  #  env:
   #     CONTAINER-REGISTRY: docker.io
    #    DOCKER_USERNAME: seyinka
     #   IMAGE_NAME: github-actions-nginx
    #needs: docker
    #runs-on: ubuntu-latest
    #steps:
    ## run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest          


##### At Workflow Level ####
 docker: 
   runs-on: ubuntu-latest
   steps:
   - name: Docker Build
     run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
   - name: Docker Login
     run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

   - name: Docker Publish
     run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 

 deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest           



